---
title: "How to Succeed on Survivor"
---

## About

Survivor is a long-running reality competition series that follows a group of castaways, as they compete is challenges and vote each other off the island. It is many people's dreams to one day be on the show, and this will serve as a guide to success if you do find yourself lucky enough to have it made it to Fiji. 

## Outwit, Outlast, Outplay: The Survivor Gospel

This is the motto of Survivor, and it's absolutely **vital** that you get to learn these words deeply, and understand how each aspect is key to becoming the sole survivor.

## Outwit

First, we have outwit. You must remain sharp and alert, even while surviving off of mere rice, coconuts, and the occasional fish. You have to be one step ahead of your castmates, aware of alliances, who's working with who, who is to be trusted, and who must be kept at arm's length — aka everyone.

## Outlast

Next, you must outlast. You have to be able to survive in brutal conditions, shoddy shelters, palm fronds for blankets, and none of the luxuries you once knew. Not to mention again, the sad array and variety of food. You have to want it most, and push yourself beyond how you have once before.

## Outplay

Last but certainly not least, outplay. Simply put, you must be better and do better. Complete your puzzles before anyone else, balance on that beam the longest, dig in and get it done. Make Father Probst proud.

